GoodToyes/GoodToyes/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GoodToyes.Models
{
    public class Cart
    { 

        public int ID { get; set; }

        public string UserID { get; set; }

        public bool CheckedOut { get; set; }

        public List<CartItem> CartItems { get; set; }

        public decimal GrandTotal { get; set; }
    }
}

GoodToyes/GoodToyes/Controllers/CartController.cs
using GoodToyes.Models;
using GoodToyes.Models.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using GoodToyes.Models.ViewModels;
using GoodToyes.ViewModels;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Authorization;


namespace GoodToyes.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly IProduct _product;
        private readonly ICart _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private IEmailSender _emailSender;
        private readonly IOrder _order;
        private IConfiguration Configuration;

        public CartController(ICart context, IProduct product, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, IEmailSender emailSender, IOrder order, IConfiguration configuration)
        {
            _context = context;
            _product = product;
            _userManager = userManager;
            _signInManager = signInManager;
            _emailSender = emailSender;
            _order = order;
            Configuration = configuration;
        }

        /// <summary>
        /// Gets cart and cart items and displays to cart page
        /// </summary>
        /// <returns>CART</returns>
        public async Task<IActionResult> Index()
        {
            
            var userId = _userManager.GetUserId(User);

            var cart = await _context.GetCart(userId);

            cart.GrandTotal = 0;
            cart.CartItems = await _context.GetCartItems(cart.ID);

            foreach(var item in cart.CartItems)
            {
                cart.GrandTotal += item.Total;

                item.Product = await _product.GetProduct(item.ProductID);
            }

            return View(cart);
        }

        /// <summary>
        /// Deletes an Item from the cart
        /// </summary>
        /// <param name="id"></param>
        /// <returns>View</returns>
        public async Task<IActionResult> DeleteCartItem(int id)
        {
            await _context.DeleteCartItem(id);

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Update quantity
        /// </summary>
        /// <param name="id"></param>
        /// <param name="quantity"></param>
        /// <returns>An view page</returns>
        public async Task<IActionResult> UpdateCartItem(int id, int quantity)
        {
            var cartItem = await _context.GetCartItem(id);

            cartItem.Quantity = quantity;

            var quan = cartItem.Quantity;

            cartItem.Total = cartItem.Product.Price * quan;

            var update = await _context.UpdateCartItem(id, cartItem);

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Shows totals and grand total and gives option to complete purchase
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> CheckOut()
        {
            ApplicationUser user = await _userManager.GetUserAsync(User);

            string userId = _userManager.GetUserId(User);

            Cart cart = await _context.GetCart(userId);


            cart.CartItems = await _context.GetCartItems(cart.ID);

            foreach (CartItem item in cart.CartItems)
            {
                cart.GrandTotal += item.Total;
                
            }
       
            return View(cart);
        }
        // <summary>
        // Checkout
        // </summary>
        // <returns>email</returns>
        public async Task<IActionResult> CheckoutReceipt()
        {

            ApplicationUser user = await _userManager.GetUserAsync(User);

            string userId = _userManager.GetUserId(User);

            Cart cart = await _context.GetCart(userId);


            cart.CartItems = await _context.GetCartItems(cart.ID);

            Models.Order newOrder = await _order.CreateOrder(user, cart.GrandTotal);

            foreach (CartItem item in cart.CartItems)
            {
                await _order.CreateOrderItem(newOrder, item);
                
            }

            await _order.UpdateOrder(newOrder.ID, newOrder);

            newOrder.OrderItems = await _order.GetOrderItems(newOrder.ID);


            //email receipt
            ApplicationUser thisUser = await _userManager.FindByEmailAsync(user.Email);

            StringBuilder sb = new StringBuilder();

            sb.AppendLine("<h1 align='center'>Order Confirmation</h1>");
            sb.AppendLine($"<h2>Good call {thisUser.FirstName}! We've got some Good Toyes on their way for your good boyes.</h2>");

            foreach (CartItem item in cart.CartItems)
            {
                cart.GrandTotal += item.Total;

                sb.AppendLine($"<h1>{item.Product.Name}</h1>");
                sb.AppendLine($"<h2>Qty: {item.Quantity}</h2>");
                sb.AppendLine($"<h2>Price: {item.Total}</h2>");
            }
            sb.AppendLine($"<h1>Grand Totoal: {cart.GrandTotal}</h1>");

            await _emailSender.SendEmailAsync(thisUser.Email, $"Order Confirmation", sb.ToString());

            //return to cart
            return View(cart);
        }

        /// <summary>
        /// Initiates the payment process and redirects to receipt email and page
        /// </summary>
        /// <param name="cardNumber"></param>
        /// <returns>Receipt View</returns>
        [HttpPost]
        public async Task<IActionResult> RunPayment(string cardNumber)
        {
            ApplicationUser user = await _userManager.GetUserAsync(User);

            string userId = _userManager.GetUserId(User);

            Cart cart = await _context.GetCart(userId);


            cart.CartItems = await _context.GetCartItems(cart.ID);

            foreach (CartItem item in cart.CartItems)
            {
                cart.GrandTotal += item.Total;

            }
            //Run Payment
            Payment payment = new Payment(Configuration);

            payment.Run(cardNumber, user, cart);

            await CheckoutReceipt();

            return View("CheckoutReceipt");
        }

        /// <summary>
        /// Clears out user's cart after order
        /// </summary>
        /// <returns>Home index view</returns>
        public async Task<IActionResult> BackToShop()
        {
            ApplicationUser user = await _userManager.GetUserAsync(User);

            string userId = _userManager.GetUserId(User);

            Cart cart = await _context.GetCart(userId);

            cart.CartItems = await _context.GetCartItems(cart.ID);

            await _context.DeleteCartItems(cart.ID);

            return RedirectToAction("Index", "Home");
        }
    }
}

GoodToyes/GoodToyes/Views/Cart/CheckOut.cshtml
@model GoodToyes.Models.Cart
@{
    Layout = "_Layout";
    var cartItems = Model.CartItems.ToList();
    
}
<section class="container center">
    <div class="pads-xs">
        <article class="media">
            <div class="media-content hide-overflow pad-top-s">
                <div class="content pad-left-s">
                    <div class="columns is-size-4 is-size-6-mobile is-mobile">
                        <div class="column is-3 is-2-mobile">
                            <strong>Product</strong>
                        </div>
                        <div class="column is-2">
                            <strong>Price</strong>
                        </div>
                        <div class="column is-2">
                            <strong>Quantity</strong>
                        </div>
                        <div class="column has-text-right">
                            <strong>Total</strong>
                        </div>
                    </div>
                </div>
            </div>
        </article>

        @foreach (var item in cartItems)
        {
            <article class="media">
                <div class="media-content hide-overflow">
                    <div class="content pad-left-s">
                        <form asp-action="UpdateCartItem" asp-route-id="@item.ID">
                            <div class="columns is-mobile">
                                <div class="column pad-top-s is-3 is-2-mobile">
                                    <strong>@item.Product.Name</strong>
                                </div>
                                <div class="column is-2">
                                    $@item.Product.Price
                                </div>
                                <div class="column is-2">
                                    @item.Quantity
                                </div>
                                <div class="column has-text-right">
                                    <span class="is-pushed-right">(@item.Product.Price x @item.Quantity) = <strong class="has-text-success">$@item.Total</strong></span>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </article>
        }
    </div>
</section>
<section>
    <div class="pads-xs">
        <hr />
    </div>
    <div class="center">
        <form method="post" asp-action="RunPayment">
            <div class="pads-s">
                <div class="columns is-centered">
                    <div class="column is-narrow">
                        <label class="label">Payment Method</label>
                        <select name="cardNumber" value="" class="dropdown-content">
                            <option value="370000000000002" class="dropdown-item">370000000000002</option>
                            <option value="6011000000000012" class="dropdown-item">6011000000000012</option>
                            <option value="4111111111111111" class="dropdown-item">4111111111111111</option>
                            <option value="5424000000000015" class="dropdown-item">5424000000000015</option>
                        </select>
                    </div>
                    @*<div class="column is-narrow">
                        <label class="label">Expiration Date</label>
                        <input type="month" min="2020-01" max="2030-12" class="input exp-input" />
                    </div>
                    <div class="column is-narrow">
                        <label class="label">CVV Code</label>
                        <input type="number" min="3" max="3" class="input quantity-input" />
                    </div>*@
                </div>
            </div>
            <div class="buttons is-centered pad-bottom-m">
                <span class="pad-right-s is-size-3 is-size-5-mobile"><strong>Grand Total:</strong> <span class="has-text-success">@Model.GrandTotal</span></span>
                <button type="submit" class="button is-success is-large">Submit</button>
            </div>
        </form>
    </div>
</section>

GoodToyes/GoodToyes/Views/Cart/Checkout.cshtml
hi

GoodToyes/GoodToyes/Views/Cart/CheckoutReceipt.cshtml
@model GoodToyes.Models.Cart
@{
    Layout = "_Layout";
    var cartItems = Model.CartItems.ToList();
    decimal total = 0m;
    foreach (var item in cartItems)
    {
        total += item.Product.Price;
    }
}
<div class="container center pads-s">
    <article class="media">
        <div class="media-content hide-overflow pad-top-s">
            <div class="content">
                <div class="columns is-size-4 is-size-6-mobile is-mobile">
                    <div class="column is-4 is-1-mobile">
                        <strong>Product</strong>
                    </div>
                    <div class="column is-2 is-1-mobile">
                        <strong>Price</strong>
                    </div>
                    <div class="column is-2 is-1-mobile has-text-centered">
                        <strong>Quantity</strong>
                    </div>
                    <div class="column is-6 is-1-mobile has-text-centered">
                        <strong class="pad-right-s">Total</strong>
                    </div>
                </div>
            </div>
        </div>
    </article>

    @foreach (var item in cartItems)
    {
     <article class="media">
         <div class="media-content hide-overflow">
             <div class="content">
                 <div class="columns is-mobile">
                     <div class="column pad-top-s is-4 is-1-mobile">
                         <strong>@item.Product.Name</strong>
                     </div>
                     <div class="column is-2 is-1-mobile">
                         $@item.Product.Price
                     </div>
                     <div class="column is-2 is-1-mobile has-text-centered">
                         @item.Quantity
                     </div>
                     <div class="column is-6 has-text-centered">
                         <strong class="has-text-success pad-right-s">$@item.Total</strong>
                     </div>
                 </div>
             </div>
         </div>
     </article>
    }
</div>
<div class="pads-xs">
    <hr />
</div>
<div class="buttons is-centered pad-bottom-xs">
    <span class="pad-right-s is-size-3 is-size-5-mobile"><strong>Grand Total:</strong> <span class="has-text-success">@total</span></span>
</div>
<div class="center is-size-3 is-size-5-mobile pad-bottom-s">
    <a asp-controller="Cart" asp-action="BackToShop" class="">Back Home</a>
</div>

GoodToyes/GoodToyes/Views/Cart/Index.cshtml
@model GoodToyes.Models.Cart
@{
    Layout = "_Layout";
    var cartItems = Model.CartItems.ToList();
    
}
<div class="pads-xs">
    <article class="media">
        <figure class="media-left pad-left-s pad-right-s mobile-hide">
            <p class="image is-64x64"></p>
        </figure>
        <div class="media-content hide-overflow pad-top-s">
            <div class="content">
                <div class="columns is-size-4 is-size-6-mobile is-mobile">
                    <div class="column is-3 is-1-mobile">
                        <strong>Product</strong>
                    </div>
                    <div class="column is-2 is-2-mobile">
                        <strong>Price</strong>
                    </div>
                    <div class="column is-3 is-1-mobile">
                        <strong>Quantity</strong>
                    </div>
                    <div class="column is-3 is-1-mobile">
                        <strong>Total</strong>
                    </div>
                </div>
            </div>
        </div>
    </article>

    @foreach (var item in cartItems)
    {<article class="media">
            <figure class="media-left pads-s mobile-hide">
                <p class="image is-64x64">
                    <img src="@item.Product.Image" />
                </p>
            </figure>
            <div class="media-content hide-overflow">
                <div class="content">
                    <form asp-action="UpdateCartItem" asp-route-id="@item.ID">
                        <div class="columns is-mobile">
                            <div class="column pad-top-s is-3 is-1-mobile">
                                <strong>@item.Product.Name</strong>
                            </div>
                            <div class="column is-2 is-2-mobile">
                                $@item.Product.Price
                            </div>
                            <div class="column is-3 is-1-mobile">
                                <input type="number" value="@item.Quantity" name="quantity" class="quantity-input input" min="1" max="10" />
                                <button type="submit" class="button is-success pad-top-xs">Update</button>
                            </div>
                            <div class="column is-3 is-1-mobile">
                                <span class="is-pushed-right">(@item.Product.Price x @item.Quantity) = <strong class="has-text-success">$@item.Total</strong></span>
                            </div>
                            <div class="pad-top-s">
                                <a asp-action="DeleteCartItem" asp-route-id="@item.ID" class="delete"></a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </article>
    }
</div>
<div class="pads-xs">
    <hr />
</div>
<div class="buttons is-centered pad-bottom-m">
    <span class="pad-right-s is-size-3 is-size-5-mobile"><strong>Grand Total:</strong> <span class="has-text-success">@Model.GrandTotal</span></span>
    <a asp-action="Checkout" class="button is-success is-large">Check Out</a>
</div>