GoodToyes/GoodToyes/Pages/Admin.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GoodToyes.Models;
using GoodToyes.Models.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GoodToyes.Pages
{
    [Authorize]
    public class AdminModel : PageModel
    {
        private IProduct _product;

        public AdminModel(IProduct product)
        {
            _product = product;
        }

        /// <summary>
        /// Deletes a product
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task OnPostDelete(int id)
        {
            await _product.DeleteProduct(id);
        }

        /// <summary>
        /// creates a new product
        /// </summary>
        /// <param name="product"></param>
        /// <returns></returns>
        public async Task OnPostCreateProduct(string url, decimal price, string name)
        {
            Product product = new Product();

            product.Name = name;

            product.Price = price;

            product.Image = url;

            await _product.CreateProduct(product);
        }

        /// <summary>
        /// updates product
        /// </summary>
        /// <param name="product"></param>
        /// <returns>updated product</returns>
        public async Task OnPostUpdateProduct(int id, string url, decimal price, string name)
        {
            var product = await _product.GetProduct(id);

            product.Name = name;

            product.Price = price;

            product.Image = url;

            await _product.UpdateProduct(product);
        }

        /// <summary>
        /// Redirects to page that displays last 10 orders
        /// </summary>
        /// <returns>View</returns>
        public IActionResult OnPostTenOrders()
        {
            return RedirectToAction("Index", "Order");
        }
        public void OnGet()
        {
        }


    }
}

GoodToyes/GoodToyes/Pages/User/UserProfile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GoodToyes.Data;
using GoodToyes.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GoodToyes.Pages
{
    public class UserProfileModel : PageModel
    {
        private UserManager<ApplicationUser> _userManager;
        private SignInManager<ApplicationUser> _signInManager;
        private GoodToyesDbContext _context;

        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime Birthdate { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public bool SpayedOrNeutered { get; set; }
        public string Email { get; set; }

        /// <summary>
        /// Constructor takes in all necessary context of user profile
        /// </summary>
        /// <param name="context">Database context</param>
        /// <param name="signInManager">Sign in manager interface</param>
        /// <param name="userManager">User manager interface</param>
        public UserProfileModel(GoodToyesDbContext context, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _context = context;
        }

        /// <summary>
        /// Updates specific user info fields
        /// </summary>
        /// <param name="firstName">User input for first name property</param>
        /// <param name="lastName">User input for last name property</param>
        /// <param name="streetAddress">User input for street address property</param>
        /// <param name="city">User input for city property</param>
        /// <param name="state">User input for city property</param>
        /// <param name="zip">User input for zip code property</param>
        /// <returns>Update task which updates the user's profile</returns>
        public async Task OnPostUpdate(string firstName, string lastName, DateTime birthDate, string streetAddress, string city, string state, string zip)
        {
            var user = await _userManager.GetUserAsync(User);

            user.FirstName = firstName;
            user.LastName = lastName;
            user.Birthdate = birthDate;
            user.StreetAddress = streetAddress;
            user.City = city;
            user.State = state;
            user.Zip = zip;

            await _userManager.UpdateAsync(user);
        }

        /// <summary>
        /// Get user information using UserManager interface
        /// </summary>
        /// <returns>Brings all user info in for use</returns>
        public async Task OnGet()
        {
            var user = await _userManager.GetUserAsync(User);

            FirstName = user.FirstName;
            LastName = user.LastName;
            Email = user.Email;
            Birthdate = user.Birthdate;
            StreetAddress = user.StreetAddress;
            City = user.City;
            State = user.State;
            Zip = user.Zip;
            SpayedOrNeutered = user.SpayedOrNeutered;
        }
    }
}

GoodToyes/GoodToyes/Pages/Admin.cshtml
@page
@model GoodToyes.Pages.AdminModel
@using GoodToyes.Models.Interfaces
@inject IProduct ProductManager
@{
    Layout = "_Layout";
    var products = await ProductManager.GetProducts();
}
<section class="hero is-small">
    <div class="hero-body">
        <div class="container has-text-centered">
            <h1 class="title is-size-1">
                Admin Page
            </h1>
        </div>
    </div>
</section>

<div class="buttons is-centered">
    <div class="field is-grouped">
        <div class="control">
            <form method="post" asp-page-handler="TenOrders">
                <button class="button is-success is-focused" type="submit">View Last 10 Orders</button>
            </form>
        </div>
    </div>
</div>

<section class="hero is-small">
    <div class="hero-body">
        <div class="container has-text-centered">
            <h1 class="title is-size-3">
                Add Products
            </h1>
        </div>
    </div>
</section>

<section class="container pads-s">
    <form method="post" asp-page-handler="CreateProduct">
        <div class="field">
            <label>Product Image URL</label>
            <div class="control">
                <input name="url" class="input" type="text" placeholder="URL" />
            </div>
        </div>

        <div class="field">
            <label>Product Name</label>
            <div class="control">
                <input name="name" class="input" type="text" placeholder="Name" />
            </div>
        </div>

        <div class="field">
            <label>Product Price</label>
            <div class="control">
                <input name="price" class="input" type="text" placeholder="Price" />
            </div>
        </div>

        <div class="buttons is-centered">
            <div class="field is-grouped">
                <div class="control">
                    <button class="button is-success is-focused" type="submit">Add Product</button>
                </div>
            </div>
        </div>
    </form>
</section>

<section class="hero is-small">
    <div class="hero-body">
        <div class="container has-text-centered">
            <h1 class="title is-size-3">
                Update Products
            </h1>
        </div>
    </div>
</section>

<div class="product-container">
    @foreach (var product in products)
    {
        <section class="container pads-s center">
            <img src="@product.Image" class="product-img" />
            <form method="post" asp-page-handler="UpdateProduct" asp-route-id="@product.ID">
                <div class="field">
                    <label>Product Image URL</label>
                    <div class="control">
                        <input name="url" class="input" type="text" value="@product.Image" />
                    </div>
                </div>

                <div class="field">
                    <label>Product Name</label>
                    <div class="control">
                        <input name="name" class="input" type="text" value="@product.Name" />
                    </div>
                </div>

                <div class="field">
                    <label>Product Price</label>
                    <div class="control">
                        <input name="price" class="input" type="text" value="@product.Price" />
                    </div>
                </div>

                <div class="buttons is-centered">
                    <div class="field is-grouped">
                        <div class="control">
                            <button class="button is-success is-focused" type="submit">Update Product</button>
                        </div>
                        <div class="control">
                            <button method="post" asp-route-id="@product.ID" asp-page-handler="Delete" class="button is-success is-danger is-outlined">Delete</button>
                        </div>
                    </div>
                </div>
            </form>
        </section>
    }
</div>

GoodToyes/GoodToyes/Pages/UserProfile.cshtml
@page
@model GoodToyes.Pages.UserProfileModel
@using GoodToyes.Models.Interfaces
@inject IOrder OrderService
@{
    Layout = "_Layout";
    //var orders = await OrderService.GetFiveOrders();
}
<section class="hero is-small">
    <div class="hero-body">
        <div class="container has-text-centered">
            <h1 class="title is-size-1">
                User Profile
            </h1>
        </div>
    </div>
</section>

<section class="pads-xs">
    <div class="container">
        <div class="field">
            <label asp-for="Email" class="label">Email</label>
            <span>@Model.Email</span>
        </div>
        <form method="post" asp-page-handler="Update" asp-route-id="">
            <div class="field">
                <label asp-for="FirstName" class="label">First Name</label>
                <div class="control">
                    <input asp-for="FirstName" class="input" type="text" placeholder="eg. Dog" />
                </div>
                <span asp-validation-for="FirstName" class="is-danger"></span>
            </div>

            <div class="field">
                <label asp-for="LastName" class="label">Last Name</label>
                <div class="control">
                    <input asp-for="LastName" class="input" type="text" placeholder="eg. Lover" />
                </div>
                <span asp-validation-for="LastName" class="is-danger"></span>
            </div>

            <div class="field">
                <label asp-for="Birthdate" class="label">Birthday</label>
                <div class="control has-icons-left">
                    <input asp-for="Birthdate" class="input" type="date" />
                    <span class="icon is-small is-left">
                        <i class="far fa-calendar"></i>
                    </span>
                </div>
                <span asp-validation-for="Birthdate" class="is-danger"></span>
            </div>

            <div class="field">
                <label asp-for="StreetAddress" class="label">Street Address</label>
                <div class="control has-icons-left">
                    <input asp-for="StreetAddress" class="input" />
                    <span class="icon is-small is-left">
                        <i class="far fa-address-card"></i>
                    </span>
                </div>
                <p class="help is-danger">
                    <span asp-validation-for="StreetAddress"></span>
                </p>
            </div>

            <div class="field">
                <label asp-for="City" class="label">City</label>
                <div class="control has-icons-left">
                    <input asp-for="City" class="input" />
                    <span class="icon is-small is-left">
                        <i class="fas fa-city"></i>
                    </span>
                </div>
                <p class="help is-danger">
                    <span asp-validation-for="City"></span>
                </p>
            </div>

            <div class="field">
                <label asp-for="State" class="label">State</label>
                <div class="control has-icons-left">
                    <input asp-for="State" class="input" />
                    <span class="icon is-small is-left">
                        <i class="fas fa-flag-usa"></i>
                    </span>
                </div>
                <p class="help is-danger">
                    <span asp-validation-for="State"></span>
                </p>
            </div>

            <div class="field">
                <label asp-for="Zip" class="label">Zip Code</label>
                <div class="control has-icons-left">
                    <input asp-for="Zip" class="input" />
                    <span class="icon is-small is-left">
                        <i class="fab fa-usps"></i>
                    </span>
                </div>
                <p class="help is-danger">
                    <span asp-validation-for="Zip"></span>
                </p>
            </div>

            @*<div class="field">
                <label asp-for="Password" class="label">Password</label>
                <div class="control has-icons-left">
                    <input asp-for="Password" class="input" type="password" placeholder="Pick a strong password" />
                    <span class="icon is-small is-left">
                        <i class="fas fa-key"></i>
                    </span>
                </div>
                <p class="help is-danger">
                    <span asp-validation-for="Password"></span>
                </p>
            </div>*@

            @*<div class="field">
                <label asp-for="ConfirmPassword" class="label">Confirm Password</label>
                <div class="control has-icons-left has-icons-right">
                    <input asp-for="ConfirmPassword" class="input" type="password" placeholder="Confirm password" />
                    <span class="icon is-small is-left">
                        <i class="fas fa-check-circle"></i>
                    </span>
                </div>
                <p class="help is-danger">
                    <span asp-validation-for="ConfirmPassword"></span>
                </p>
            </div>*@

            <div class="field">
                <label class="label has-text-success">Special Deals</label>
                <div class="control">
                    <label asp-for="SpayedOrNeutered" class="checkbox">
                        <input asp-for="SpayedOrNeutered" type="checkbox">
                        <span class="">
                            Is your pup spayed or neutered?
                        </span>
                    </label>
                </div>
            </div>

            <div class="buttons is-centered">
                <div class="field is-grouped">
                    <div class="control">
                        <button class="button is-success is-focused" type="submit">Update</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>