GoodToyes/GoodToyes/Pages/User/OrderHistory.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GoodToyes.Data;
using GoodToyes.Models;
using GoodToyes.Models.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GoodToyes.Pages.User
{
    public class OrderHistoryModel : PageModel
    {
        private IOrder _orderService;
        private UserManager<ApplicationUser> _userManager;
        private SignInManager<ApplicationUser> _signInManager;
        private GoodToyesDbContext _context;

        public List<Order> Orders { get; set; }
        public List<OrderItem> OrderItems { get; set; }

        public OrderHistoryModel(GoodToyesDbContext context, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager, IOrder orderService)
        {
            _context = context;
            _signInManager = signInManager;
            _userManager = userManager;
            _orderService = orderService;
        }

        /// <summary>
        /// Gets that last 5 orders that a user made
        /// </summary>
        /// <returns>A list of orders</returns>
        public async Task OnGet()
        {
            var user = await _userManager.GetUserAsync(User);

            Orders = await _orderService.GetFiveOrders(user.Id);
        }
    }
}

GoodToyes/GoodToyes/Pages/User/UpdatePassword.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using GoodToyes.Models;
using GoodToyes.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GoodToyes.Pages.User
{
    public class UpdatePasswordModel : PageModel
    {
        private UserManager<ApplicationUser> _userManager;
        private SignInManager<ApplicationUser> _signInManager;

        [Required]
        [BindProperty]
        [DataType(DataType.Password)]
        public string NewPassword { get; set; }

        [BindProperty]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        [BindProperty]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm Password")]
        [Compare("Password", ErrorMessage = "Does Not Match")]
        public string ConfirmPassword { get; set; }

        public UpdatePasswordModel(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        /// <summary>
        /// Updates the password
        /// </summary>
        /// <returns></returns>
        public async Task OnPostPassword()
        {
            var user = await _userManager.GetUserAsync(User);

            if (NewPassword == ConfirmPassword)
            {
                await _userManager.ChangePasswordAsync(user, Password, NewPassword);
            } 
        }

        /// <summary>
        /// Takes user to their dashboard
        /// </summary>
        /// <returns>A user</returns>
        public async Task OnGet()
        {
            var user = await _userManager.GetUserAsync(User);
        }
    }
}

GoodToyes/GoodToyes/Pages/User/UserProfile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GoodToyes.Data;
using GoodToyes.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GoodToyes.Pages
{
    public class UserProfileModel : PageModel
    {
        private UserManager<ApplicationUser> _userManager;
        private SignInManager<ApplicationUser> _signInManager;
        private GoodToyesDbContext _context;

        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime Birthdate { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public bool SpayedOrNeutered { get; set; }
        public string Email { get; set; }

        /// <summary>
        /// Constructor takes in all necessary context of user profile
        /// </summary>
        /// <param name="context">Database context</param>
        /// <param name="signInManager">Sign in manager interface</param>
        /// <param name="userManager">User manager interface</param>
        public UserProfileModel(GoodToyesDbContext context, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _context = context;
        }

        /// <summary>
        /// Updates specific user info fields
        /// </summary>
        /// <param name="firstName">User input for first name property</param>
        /// <param name="lastName">User input for last name property</param>
        /// <param name="streetAddress">User input for street address property</param>
        /// <param name="city">User input for city property</param>
        /// <param name="state">User input for city property</param>
        /// <param name="zip">User input for zip code property</param>
        /// <returns>Update task which updates the user's profile</returns>
        public async Task OnPostUpdate(string firstName, string lastName, DateTime birthDate, string streetAddress, string city, string state, string zip)
        {
            var user = await _userManager.GetUserAsync(User);

            user.FirstName = firstName;
            user.LastName = lastName;
            user.Birthdate = birthDate;
            user.StreetAddress = streetAddress;
            user.City = city;
            user.State = state;
            user.Zip = zip;

            await _userManager.UpdateAsync(user);
        }

        /// <summary>
        /// Get user information using UserManager interface
        /// </summary>
        /// <returns>Brings all user info in for use</returns>
        public async Task OnGet()
        {
            var user = await _userManager.GetUserAsync(User);

            FirstName = user.FirstName;
            LastName = user.LastName;
            Email = user.Email;
            Birthdate = user.Birthdate;
            StreetAddress = user.StreetAddress;
            City = user.City;
            State = user.State;
            Zip = user.Zip;
            SpayedOrNeutered = user.SpayedOrNeutered;
        }
    }
}

GoodToyes/GoodToyes/Pages/User/OrderHistory.cshtml
@page
@model GoodToyes.Pages.User.OrderHistoryModel
@{
    Layout = "_Layout";
}
<div class="container center pads-s">
    <article class="media">
        <div class="media-content hide-overflow pad-top-s">
            <div class="content">
                <div class="columns is-size-4 is-size-6-mobile is-mobile">
                    <div class="column is-4 is-1-mobile">
                        <strong>Date</strong>
                    </div>
                    <div class="column is-2 is-1-mobile">
                        <strong>Products</strong>
                    </div>
                    <div class="column is-6 is-1-mobile has-text-centered">
                        <strong class="pad-right-s">Total</strong>
                    </div>
                </div>
            </div>
        </div>
    </article>
    @foreach (var order in Model.Orders)
    {
        <article class="media">
            <div class="media-content hide-overflow pad-top-s">
                <div class="content">
                    <div class="columns is-size-4 is-size-6-mobile is-mobile">
                        <div class="column is-4 is-1-mobile">
                            <strong>@order.OrderDate.ToShortDateString()</strong>
                        </div>
                        <div class="column is-2 is-1-mobile">
                            <strong>@order.OrderItems</strong>
                        </div>
                        <div class="column is-6 is-1-mobile has-text-centered">
                            <strong class="pad-right-s">@order.GrandTotal</strong>
                        </div>
                    </div>
                </div>
            </div>
        </article>
    }
</div>

GoodToyes/GoodToyes/Pages/User/UpdatePassword.cshtml
@page
@model GoodToyes.Pages.User.UpdatePasswordModel
@{
    Layout = "_Layout";
}
<section class="hero is-small">
    <div class="hero-body">
        <div class="container has-text-centered">
            <h1 class="title is-size-1">
                Update Password
            </h1>
        </div>
    </div>
</section>

<section class="pad-bottom-m">
    <form method="post" asp-page-handler="Password">
        <div class="container pads-s">
            <div class="field">
                <label asp-for="Password" class="label">Current Password</label>
                <div class="control has-icons-left">
                    <input asp-for="Password" class="input" type="password" placeholder="Current Password" />
                    <span class="icon is-small is-left">
                        <i class="fas fa-key"></i>
                    </span>
                </div>
                <p class="help is-danger">
                    <span asp-validation-for="Password"></span>
                </p>
            </div>

            <div class="container">
                <div class="field">
                    <label asp-for="NewPassword" class="label">New Password</label>
                    <div class="control has-icons-left">
                        <input asp-for="NewPassword" class="input" type="password" placeholder="Pick a strong password" />
                        <span class="icon is-small is-left">
                            <i class="fas fa-key"></i>
                        </span>
                    </div>
                    <p class="help is-danger">
                        <span asp-validation-for="NewPassword"></span>
                    </p>
                </div>

                <div class="field">
                    <label asp-for="ConfirmPassword" class="label">Confirm New Password</label>
                    <div class="control has-icons-left has-icons-right">
                        <input asp-for="ConfirmPassword" class="input" type="password" placeholder="Confirm password" />
                        <span class="icon is-small is-left">
                            <i class="fas fa-check-circle"></i>
                        </span>
                    </div>
                    <p class="help is-danger">
                        <span asp-validation-for="ConfirmPassword"></span>
                    </p>
                </div>

                <div class="buttons is-centered">
                    <div class="field is-grouped">
                        <div class="control">
                            <button class="button is-success" type="submit">Submit</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</section>

GoodToyes/GoodToyes/Pages/User/UserProfile.cshtml
@page
@model GoodToyes.Pages.UserProfileModel
@{
    Layout = "_Layout";
}
<section class="hero is-small">
    <div class="hero-body">
        <div class="container has-text-centered">
            <h1 class="title is-size-1">
                User Profile
            </h1>
        </div>
    </div>
</section>

<section class="pads-xs">
    <div class="container">
        <div class="field">
            <label asp-for="Email" class="label">Email</label>
            <span>@Model.Email</span>
        </div>

        <div class="field">
            <a href="~/User/UpdatePassword">Update Password</a>
        </div>

        <form method="post" asp-page-handler="Update" asp-route-id="">
            <div class="field">
                <label asp-for="FirstName" class="label">First Name</label>
                <div class="control">
                    <input asp-for="FirstName" class="input" type="text" placeholder="eg. Dog" />
                </div>
                <span asp-validation-for="FirstName" class="is-danger"></span>
            </div>

            <div class="field">
                <label asp-for="LastName" class="label">Last Name</label>
                <div class="control">
                    <input asp-for="LastName" class="input" type="text" placeholder="eg. Lover" />
                </div>
                <span asp-validation-for="LastName" class="is-danger"></span>
            </div>

            <div class="field">
                <label asp-for="Birthdate" class="label">Birthday</label>
                <div class="control has-icons-left">
                    <input asp-for="Birthdate" class="input" type="date" />
                    <span class="icon is-small is-left">
                        <i class="far fa-calendar"></i>
                    </span>
                </div>
                <span asp-validation-for="Birthdate" class="is-danger"></span>
            </div>

            <div class="field">
                <label asp-for="StreetAddress" class="label">Street Address</label>
                <div class="control has-icons-left">
                    <input asp-for="StreetAddress" class="input" />
                    <span class="icon is-small is-left">
                        <i class="far fa-address-card"></i>
                    </span>
                </div>
                <p class="help is-danger">
                    <span asp-validation-for="StreetAddress"></span>
                </p>
            </div>

            <div class="field">
                <label asp-for="City" class="label">City</label>
                <div class="control has-icons-left">
                    <input asp-for="City" class="input" />
                    <span class="icon is-small is-left">
                        <i class="fas fa-city"></i>
                    </span>
                </div>
                <p class="help is-danger">
                    <span asp-validation-for="City"></span>
                </p>
            </div>

            <div class="field">
                <label asp-for="State" class="label">State</label>
                <div class="control has-icons-left">
                    <input asp-for="State" class="input" />
                    <span class="icon is-small is-left">
                        <i class="fas fa-flag-usa"></i>
                    </span>
                </div>
                <p class="help is-danger">
                    <span asp-validation-for="State"></span>
                </p>
            </div>

            <div class="field">
                <label asp-for="Zip" class="label">Zip Code</label>
                <div class="control has-icons-left">
                    <input asp-for="Zip" class="input" />
                    <span class="icon is-small is-left">
                        <i class="fab fa-usps"></i>
                    </span>
                </div>
                <p class="help is-danger">
                    <span asp-validation-for="Zip"></span>
                </p>
            </div>

            <div class="field">
                <label class="label has-text-success">Special Deals</label>
                <div class="control">
                    <label asp-for="SpayedOrNeutered" class="checkbox">
                        <input asp-for="SpayedOrNeutered" type="checkbox">
                        <span class="">
                            Is your pup spayed or neutered?
                        </span>
                    </label>
                </div>
            </div>

            <div class="buttons is-centered">
                <div class="field is-grouped">
                    <div class="control">
                        <button class="button is-success is-focused" type="submit">Update</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>